version: "3"

services:
  bot:
    container_name: vibr
    env_file: .env
    restart: unless-stopped
    depends_on:
      - lavalink
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/bot/logs
      - /var/run/postgresql:/var/run/postgresql
      - ./vibr:/bot/vibr
    network_mode: host
  lavalink:
    container_name: lavalink
    restart: unless-stopped
    build:
      context: lavalink
      dockerfile: Dockerfile
    network_mode: host
