version: "3"

services:
  bot:
    container_name: vibr-beta
    env_file: .env
    restart: unless-stopped
    depends_on:
      - lavalink
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/bot/logs
      - ./vibr:/bot/vibr
    environment:
      LAVALINK_HOST: 127.0.0.1
      LAVALINK_PORT: 6968
      DB_URI: postgres://postgres:postgres@localhost:5433/bot
    network_mode: host
  lavalink:
    container_name: lavalink-beta
    restart: unless-stopped
    build:
      context: lavalink
      dockerfile: beta.Dockerfile
    network_mode: host
    volumes:
      - ./logs/lava:/opt/Lavalink/logs
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bot
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    network_mode: host
    command: -p 5433
