version: "3"

services:
  gateway-proxy:
    volumes:
      - ./gateway-proxy/config.json:/config.json
  postgres:
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  api:
    ports:
      - 8000:8000
    environment:
      REDIRECT_URI: http://localhost:8000
