version: "3"

services:
  bot:
    container_name: vibr
    env_file: .env
    restart: unless-stopped
    depends_on:
      - lavalink
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/bot/logs
      - /var/run/postgresql:/var/run/postgresql
      - ./vibr:/bot/vibr
    network_mode: host
    environment:
      LAVALINK_HOST: 127.0.0.1
      IPC_BIND: 127.0.0.1
      IPC_PORT: 8765
  lavalink:
    container_name: lavalink
    restart: unless-stopped
    build:
      context: lavalink
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ./logs/lava:/opt/Lavalink/logs
  api:
    env_file: .env
    restart: unless-stopped
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "3069:3069"
    volumes:
      - ./logs/server:/server/logs
    environment:
      IPC_SERVER: 127.0.0.1
      IPC_PORT: 8765
      SERVER_BIND: 127.0.0.1
      SERVER_PORT: 3069
