version: "3"

services:
  bot:
    container_name: vibr
    env_file: .env
    restart: unless-stopped
    depends_on:
      - lavalink
      - postgres
    links:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/bot/logs
      - ./vibr:/bot/vibr
    environment:
      LAVALINK_HOST: 127.0.0.1
      DB_URI: postgresql://postgres:postgres@127.0.0.1:5433/bot
    network_mode: host
  lavalink:
    container_name: lavalink
    restart: unless-stopped
    build:
      context: lavalink
      dockerfile: Dockerfile
    network_mode: host
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bot
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    network_mode: host
    ports:
      - "5433:5432"
