version: "3"

services:
  bot:
    depends_on:
      - postgres
      - keydb
      - lavalink
      - gateway-proxy
    build:
      context: .
      dockerfile: vibr/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    pull_policy: build
    environment:
      TOKEN: ${TOKEN:?No TOKEN provided}
      TOTAL_CLUSTERS: ${TOTAL_CLUSTERS:-1}
      LAVALINK_FILE: lavalink/alpha.nodes.yml
      # DB_URI: postgresql://postgres:postgres@postgres:5432/bot
      GW_PROXY: ws://gateway-proxy:7878
      PROXY_HTTP: http://gateway-proxy:7878
      PASSWORD: ${PASSWORD:?No password for LOCAL lavalink provided}
      REDIS_URL: redis://keydb:6379
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID:?No Spotify Client ID provided}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET:?No Spotify Client secret provided}
      LOG_CHANNEL: "1101963855141281912"
    ports:
      - 127.0.0.1:${PROMETHEUS_PORTS:-6781}:9000
  gateway-proxy:
    image: ghcr.io/boting-devs/gateway-proxy:vibr-x86-64
    environment:
      TOKEN: $TOKEN
    volumes:
      - ./gateway-proxy/config.json:/config.json
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bot
      PGDATA: /var/lib/postgresql/data/pgdata
  keydb:
    image: eqalpha/keydb
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    pull_policy: build
    environment:
      DB_URI: postgresql://postgres:postgres@postgres:5432/bot
  lavalink:
    extends:
      file: lavalink/nodes/base.yml
      service: lavalink
