version: "3"

x-restart-policy:
  &restart_policy
  restart: unless-stopped

services:
  bot:
    <<: *restart_policy
    environment:
      LAVALINK_FILE: lavalink/prod.nodes.yml
      EU_PASSWORD: ${EU_PASSWORD:?No EU password provided}
      TOPGG_VOTING: true
      # Simply for ensuring presence
      PROMETHEUS_PORTS: ${PROMETHEUS_PORTS:?No Prometheus ports provided}
      TOPGG_TOKEN: ${TOPGG_AUTH:?No top.gg API token provided}
      LOG_CHANNEL: "939853360289419284"
      PROD: true
    deploy:
      replicas: $TOTAL_CLUSTERS
  gateway-proxy:
    <<: *restart_policy
    ports:
      - 127.0.0.1:5784:7878
  postgres:
    <<: *restart_policy
    volumes:
      - vibr-db:/var/lib/postgresql/data
  api:
    <<: *restart_policy
    ports:
      - 127.0.0.1:5782:8000
    environment:
      TOPGG_ENABLED: true
      DISCORD_TOKEN: $TOPGG_DISCORD_TOKEN
      VOTE_CHANNEL: "946324179605684235"
      TOPGG_SECRET: ${TOPGG_SECRET:?No top.gg secret provided}
  lavalink:
    <<: *restart_policy
    network_mode: host
    environment:
      SERVER_PORT: 5783
      LAVALINK_SERVER_RATELIMIT_IP_BLOCKS_0: ${IP_BLOCK:?No IPv6 block provided}
      LAVALINK_SERVER_STRATEGY: LoadBalance
      LAVALINK_SERVER_SEARCH_TRIGGERS_FAIL: true

volumes:
  vibr-db:
