version: "3"

services:
  bot:
    environment:
      LAVALINK_FILE: lavalink/beta.nodes.yml
      SPOTIFY_REDIRECT_URL: https://vibr-oauth.boting.xyz
  api:
    ports:
      - 127.0.0.1:6796:8000
    environment:
      REDIRECT_URI: https://vibr-oauth.boting.xyz
  gateway-proxy:
    volumes:
      - ./gateway-proxy/config.json:/config.json
    ports:
      - 127.0.0.1:6784:7878
  postgres:
    volumes:
      - vibr-beta-db:/var/lib/postgresql/data
  lavalink:
    network_mode: host
    environment:
      SERVER_PORT: 6783
      LAVALINK_SERVER_RATELIMIT_IP_BLOCKS_0: ${IP_BLOCK:?No IPv6 block provided}
      LAVALINK_SERVER_STRATEGY: LoadBalance
      LAVALINK_SERVER_SEARCH_TRIGGERS_FAIL: true
      METRICS_PROMETHEUS_ENABLED: true

volumes:
  vibr-beta-db:
