version: "3"

services:
  gateway-proxy:
    volumes:
      - ./gateway-proxy/config.json:/config.json
  postgres:
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  lavalink:
    environment:
      METRICS_PROMETHEUS_ENABLED: false
  api:
    ports:
      - 127.0.0.1:6782:8000
