version: "3"

x-restart-policy:
  &restart-policy
  restart: unless-stopped

services:
  bot:
    <<: *restart-policy
    depends_on:
      - lavalink
      - postgres
      - gateway-proxy
    build: .
    volumes:
      - ./logs:/bot/logs
    environment:
      LAVALINK_HOST: lavalink
      DB_URI: postgresql://postgres:postgres@postgres:5432/bot
      GW_PROXY: ws://gateway-proxy:7878
      TOKEN: $TOKEN
  lavalink:
    <<: *restart-policy
    build:
      context: lavalink
      dockerfile: alpha.Dockerfile
    volumes:
      - ./logs/lava:/opt/Lavalink/logs
  postgres:
    <<: *restart-policy
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bot
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  gateway-proxy:
    <<: *restart-policy
    image: gelbpunkt/gateway-proxy:x86-64
    volumes:
      - ./gateway-proxy/noshard.config.json:/config.json
    environment:
      TOKEN: $TOKEN
