version: "3"

services:
  bot:
    container_name: vibr-alpha
    env_file: .env
    restart: unless-stopped
    depends_on:
      - lavalink
      - postgres
    links:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/bot/logs
      - ./vibr:/bot/vibr
    environment:
      LAVALINK_HOST: lavalink-alpha
      DB_URI: postgresql://postgres:postgres@postgres:5432/bot
  lavalink:
    container_name: lavalink-alpha
    restart: unless-stopped
    build:
      context: lavalink
      dockerfile: alpha.Dockerfile
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bot
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data
