version: "3"

services:
  bot:
    depends_on:
      - postgres
      - keydb
      - manager
      - lavalink
      - gateway-proxy
    build:
      context: .
      dockerfile: vibr/Dockerfile
    volumes:
      - ./logs:/bot/logs
      - /var/run/docker.sock:/var/run/docker.sock
    pull_policy: build
    environment:
      TOKEN: $TOKEN
      TOTAL_CLUSTERS: ${TOTAL_CLUSTERS:-1}
      LAVALINK_FILE: lavalink/alpha.nodes.yml
      DB_URI: postgresql://postgres:postgres@postgres:5432/bot
      GW_PROXY: ws://gateway-proxy:7878
      PROXY_HTTP: http://gateway-proxy:7878
      PASSWORD: $PASSWORD
      REDIS_URL: redis://keydb:6379
  gateway-proxy:
    image: ghcr.io/ooliver1/gateway-proxy:x86-64
    environment:
      TOKEN: $TOKEN
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bot
      PGDATA: /var/lib/postgresql/data/pgdata
  keydb:
    image: eqalpha/keydb
  manager:
    build:
      context: .
      dockerfile: manager/Dockerfile
    volumes:
      - ./logs:/manager/logs
    depends_on:
      - keydb
    pull_policy: build
    environment:
      REDIS_URL: redis://keydb:6379
  lavalink:
    image: ghcr.io/drschlaubi/lavalink:feature-kotlinx-serialization
    volumes:
      - ./logs/lava:/opt/Lavalink/logs
    environment:
      JDK_JAVA_OPTIONS: -Xmx2G
      SERVER_PORT: 6969
      SERVER_ADDRESS: 0.0.0.0
      LAVALINK_SERVER_PASSWORD: $PASSWORD
      LAVALINK_SERVER_FRAMEBUFFERDURATION: 5000
      LAVALINK_SERVER_RESAMPLINGQUALITY: LOW
      LAVALINK_SERVER_YOUTUBEPLAYLISTLOADLIMIT: 5
      LAVALINK_PLUGINS_0_DEPENDENCY: "com.github.TopiSenpai.LavaSrc:lavasrc-plugin:85b39d130692e0fb96c61f5ed518ad3c1e4eecd6"
      LAVALINK_PLUGINS_0_REPOSITORY: "https://jitpack.io"
      PLUGINS_LAVASRC_PROVIDERS_0: "dzisrc:%ISRC%"
      PLUGINS_LAVASRC_PROVIDERS_1: "dzsearch:%QUERY%"
      PLUGINS_LAVASRC_PROVIDERS_2: 'ytsearch:"%ISRC%"'
      PLUGINS_LAVASRC_PROVIDERS_3: "ytsearch:%QUERY%"
      PLUGINS_LAVASRC_SOURCES_SPOTIFY: true
      PLUGINS_LAVASRC_SOURCES_APPLEMUSIC: true
      PLUGINS_LAVASRC_SOURCES_DEEZER: true
      PLUGINS_LAVASRC_SOURCES_YANDEXMUSIC: true
      PLUGINS_LAVASRC_SPOTIFY_CLIENTID: $SPOTIFY_CLIENT_ID
      PLUGINS_LAVASRC_SPOTIFY_CLIENTSECRET: $SPOTIFY_CLIENT_SECRET
      PLUGINS_LAVASRC_SPOTIFY_COUNTRYCODE: US
      PLUGINS_LAVASRC_SPOTIFY_PLAYLISTLOADLIMIT: 5
      PLUGINS_LAVASRC_SPOTIFY_ALBUMLOADLIMIT: 10
      PLUGINS_LAVASRC_APPLEMUSIC_PLAYLISTLOADLIMIT: 2
      PLUGINS_LAVASRC_APPLEMUSIC_ALBUMLOADLIMIT: 2
      PLUGINS_LAVASRC_DEEZER_MASTERDECRYPTIONKEY: $DEEZER_KEY
      PLUGINS_LAVASRC_YANDEXMUSIC_ACCESSTOKEN: $YANDEX_TOKEN
      METRICS_PROMETHEUS_ENABLED: false
      LOGGING_FILE_PATH: ./logs/
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_LAVALINK: INFO
      LOGGING_REQUEST_INCLUDEHEADERS: false
      LOGGING_LOGBACK_ROLLINGPOLICY_MAXFILESIZE: 100MB
      LOGGING_LOGBACK_ROLLINGPOLICY_MAXHISTORY: 30
