"""add spotify fields to user

Revision ID: 6669e1c709a5
Revises: 6f98c023675d
Create Date: 2023-05-14 00:10:03.054509

"""
# pyright: reportPrivateImportUsage=false
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6669e1c709a5"
down_revision = "6f98c023675d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("spotify_access_token", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("spotify_refresh_token", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("spotify_activation_time", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_column("users", "spotify")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "spotify", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "spotify_activation_time")
    op.drop_column("users", "spotify_refresh_token")
    op.drop_column("users", "spotify_access_token")
    # ### end Alembic commands ###
