"""add player table

Revision ID: 6f98c023675d
Revises: 552612cc0faf
Create Date: 2023-04-26 21:41:59.262511

"""
# pyright: reportPrivateImportUsage=false
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6f98c023675d"
down_revision = "552612cc0faf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("volume", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("channel_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("players")
    # ### end Alembic commands ###
