"""add stats

Revision ID: 7c93553d9e92
Revises: fe54c46cdb5b
Create Date: 2023-02-16 23:11:15.396212

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7c93553d9e92"
down_revision = "fe54c46cdb5b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hourly_stats",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("guilds", sa.Integer(), nullable=False),
        sa.Column("commands", sa.Integer(), nullable=False),
        sa.Column("total_songs", sa.Integer(), nullable=False),
        sa.Column("listeners", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("time"),
    )
    op.create_table(
        "node_stats",
        sa.Column("time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("node", sa.String(length=25), nullable=False),
        sa.Column("active_players", sa.Integer(), nullable=False),
        sa.Column("total_players", sa.Integer(), nullable=False),
        sa.Column("lavalink_load", sa.SmallInteger(), nullable=False),
        sa.Column("system_load", sa.SmallInteger(), nullable=False),
        sa.Column("memory_used", sa.SmallInteger(), nullable=False),
        sa.Column("memory_allocated", sa.SmallInteger(), nullable=False),
        sa.Column("memory_percentage", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["time"],
            ["hourly_stats.time"],
            name="fk_node_stats_hourly_stats_time_time",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("node"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("node_stats")
    op.drop_table("hourly_stats")
    # ### end Alembic commands ###
