"""add custom playlists

Revision ID: 99bded196ef0
Revises: 956abcb8f455
Create Date: 2023-05-21 15:28:26.165799

"""
# pyright: reportPrivateImportUsage=false
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "99bded196ef0"
down_revision = "956abcb8f455"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "songs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "lavalink_id",
            sa.LargeBinary(length=300),
            nullable=False,
            unique=True,
            index=True,
        ),
        sa.Column("likes", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playlists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("owner", sa.BigInteger(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner"],
            ["users.id"],
            name="fk_playlists_users_id_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "owner", name="uc_playlists_name_owner"),
    )
    op.create_table(
        "playlists_to_songs",
        sa.Column("added", sa.DateTime(timezone=True), nullable=False),
        sa.Column("song", sa.Integer(), nullable=True),
        sa.Column("playlist", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["playlist"],
            ["playlists.id"],
            name="fk_playlists_to_songs_playlists_playlist_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["song"],
            ["songs.id"],
            name="fk_playlists_to_songs_songs_song_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "song", "playlist", name="uc_playlists_to_songs_song_playlist"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playlists_to_songs")
    op.drop_table("playlists")
    op.drop_table("songs")
    # ### end Alembic commands ###
