"""add spotify fields to User

Revision ID: b1af526da50c
Revises: 6f98c023675d
Create Date: 2023-05-10 19:04:54.284427

"""
# pyright: reportPrivateImportUsage=false
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b1af526da50c"
down_revision = "6f98c023675d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("spotify_access_token", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("spotify_refresh_token", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("spotify_token_expires", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_column("users", "spotify")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "spotify", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "spotify_token_expires")
    op.drop_column("users", "spotify_refresh_token")
    op.drop_column("users", "spotify_access_token")
    # ### end Alembic commands ###
