"""init

Revision ID: f02c4db0ff19
Revises: 
Create Date: 2023-02-13 22:36:36.669368

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f02c4db0ff19"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blacklist_guilds",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "blacklist_users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "commands",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("command", sa.String(length=255), nullable=False),
        sa.Column("guild", sa.BigInteger(), nullable=False),
        sa.Column("channel", sa.BigInteger(), nullable=False),
        sa.Column("member", sa.BigInteger(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "command",
            "guild",
            "channel",
            "member",
            name="uc_commands_command_guild_channel_member",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("commands")
    op.drop_table("blacklist_users")
    op.drop_table("blacklist_guilds")
    # ### end Alembic commands ###
