version: "3"

x-restart-policy: &restart_policy
  restart: no

services:
  lavalink:
    <<: *restart_policy
    image: ghcr.io/lavalink-devs/lavalink:4.0.5
    entrypoint:
      [
        "java",
        "-Djdk.tls.client.protocols=TLSv1.1,TLSv1.2",
        "-Xmx${MEM:-2G}",
        "-jar",
        "Lavalink.jar",
      ]
    environment:
      SERVER_PORT: 6969
      SERVER_ADDRESS: 0.0.0.0
      LAVALINK_SERVER_PASSWORD: $PASSWORD
      LAVALINK_SERVER_FRAME_BUFFER_DURATION: 5000
      LAVALINK_SERVER_RESAMPLING_QUALITY: LOW
      LAVALINK_SERVER_YOUTUBE_PLAYLIST_LOAD_LIMIT: 5
      LAVALINK_PLUGINS_0_DEPENDENCY: "com.github.topi314.lavasrc:lavasrc-plugin:4.1.1"
      LAVALINK_PLUGINS_1_DEPENDENCY: "dev.lavalink.youtube:youtube-plugin:1.5.0"
      LAVALINK_SERVER_SOURCES_YOUTUBE: false
      PLUGINS_YOUTUBE_ENABLED: true
      # default is "MUSIC", "WEB", "ANDROID", "TVHTML5EMBEDDED"
      # IOS could be something to try if there are issues, but it requires transcoding
      # ANDROID_TESTSUITE may have less blocking, but does not load all kinds of videos
      # TVHTML5EMBEDDED is the alternative to logging in for age restricted
      # logging in makes it easier to get blocked and is barely supported on yt anyway (not in the plugin)
      # PLUGINS_YOUTUBE_CLIENTS_n: ...
      # expected these to be the default as they're shown in the example config
      # there are no default client options however
      # there will avoid using multiple clients when the next one may
      # - not support that feature
      # - not make it any better
      PLUGINS_YOUTUBE_WEB_PLAYBACK: false
      # tv should only be used for playing age restricted to keep it from being blocked
      PLUGINS_YOUTUBE_TVHTML5EMBEDDED_PLAYLIST_LOADING: false
      PLUGINS_YOUTUBE_TVHTML5EMBEDDED_VIDEO_LOADING: false
      PLUGINS_YOUTUBE_TVHTML5EMBEDDED_SEARCHING: false
      PLUGINS_LAVASRC_PROVIDERS_0: "dzisrc:%ISRC%"
      PLUGINS_LAVASRC_PROVIDERS_1: "dzsearch:%QUERY%"
      PLUGINS_LAVASRC_PROVIDERS_2: 'ytsearch:"%ISRC%"'
      PLUGINS_LAVASRC_PROVIDERS_3: "ytsearch:%QUERY%"
      PLUGINS_LAVASRC_SOURCES_SPOTIFY: true
      PLUGINS_LAVASRC_SOURCES_APPLEMUSIC: true
      PLUGINS_LAVASRC_SOURCES_DEEZER: true
      PLUGINS_LAVASRC_SOURCES_YANDEXMUSIC: false
      PLUGINS_LAVASRC_SPOTIFY_CLIENT_ID: $SPOTIFY_CLIENT_ID
      PLUGINS_LAVASRC_SPOTIFY_CLIENT_SECRET: $SPOTIFY_CLIENT_SECRET
      PLUGINS_LAVASRC_SPOTIFY_COUNTRY_CODE: US
      PLUGINS_LAVASRC_SPOTIFY_PLAYLIST_LOAD_LIMIT: 5
      PLUGINS_LAVASRC_SPOTIFY_ALBUM_LOAD_LIMIT: 10
      PLUGINS_LAVASRC_APPLEMUSIC_PLAYLIST_LOAD_LIMIT: 2
      PLUGINS_LAVASRC_APPLEMUSIC_ALBUM_LOAD_LIMIT: 2
      PLUGINS_LAVASRC_APPLEMUSIC_MEDIAAPITOKEN: ${APPLE_TOKEN:?No Apple token provided}
      PLUGINS_LAVASRC_DEEZER_MASTER_DECRYPTION_KEY: ${DEEZER_KEY:?No Deezer key provided}
      # PLUGINS_LAVASRC_YANDEXMUSIC_ACCESSTOKEN: $YANDEX_TOKEN
      METRICS_PROMETHEUS_ENABLED: true
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_LAVALINK: INFO
      LOGGING_REQUEST_ENABLED: true
      LOGGING_LOGBACK_ROLLING_POLICY_MAX_FILE_SIZE: 100MB
      LOGGING_LOGBACK_ROLLING_POLICY_MAX_HISTORY: 30
