version: "3"

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  lavalink:
    <<: *restart_policy
    image: ghcr.io/freyacodes/lavalink:v4
    entrypoint:
      [
        "java",
        "-Djdk.tls.client.protocols=TLSv1.1,TLSv1.2",
        "-Xmx${MEM:-2G}",
        "-jar",
        "Lavalink.jar",
      ]
    environment:
      SERVER_PORT: 6969
      SERVER_ADDRESS: 0.0.0.0
      LAVALINK_SERVER_PASSWORD: $PASSWORD
      LAVALINK_SERVER_FRAME_BUFFER_DURATION: 5000
      LAVALINK_SERVER_RESAMPLING_QUALITY: LOW
      LAVALINK_SERVER_YOUTUBE_PLAYLIST_LOAD_LIMIT: 5
      LAVALINK_PLUGINS_0_DEPENDENCY: "com.github.TopiSenpai.LavaSrc:lavasrc-plugin:85b39d130692e0fb96c61f5ed518ad3c1e4eecd6"
      LAVALINK_PLUGINS_0_REPOSITORY: "https://jitpack.io"
      LAVALINK_SERVER_YOUTUBE_CONFIG_EMAIL: "musicfixthebot@gmail.com"
      LAVALINK_SERVER_YOUTUBE_CONFIG_PASSWORD: "ChitChat100"
      PLUGINS_LAVASRC_PROVIDERS_0: "dzisrc:%ISRC%"
      PLUGINS_LAVASRC_PROVIDERS_1: "dzsearch:%QUERY%"
      PLUGINS_LAVASRC_PROVIDERS_2: 'ytsearch:"%ISRC%"'
      PLUGINS_LAVASRC_PROVIDERS_3: "ytsearch:%QUERY%"
      PLUGINS_LAVASRC_SOURCES_SPOTIFY: true
      PLUGINS_LAVASRC_SOURCES_APPLEMUSIC: true
      PLUGINS_LAVASRC_SOURCES_DEEZER: true
      PLUGINS_LAVASRC_SOURCES_YANDEXMUSIC: false
      PLUGINS_LAVASRC_SPOTIFY_CLIENT_ID: $SPOTIFY_CLIENT_ID
      PLUGINS_LAVASRC_SPOTIFY_CLIENT_SECRET: $SPOTIFY_CLIENT_SECRET
      PLUGINS_LAVASRC_SPOTIFY_COUNTRY_CODE: US
      PLUGINS_LAVASRC_SPOTIFY_PLAYLIST_LOAD_LIMIT: 5
      PLUGINS_LAVASRC_SPOTIFY_ALBUM_LOAD_LIMIT: 10
      PLUGINS_LAVASRC_APPLE_MUSIC_PLAYLIST_LOAD_LIMIT: 2
      PLUGINS_LAVASRC_APPLE_MUSIC_ALBUM_LOAD_LIMIT: 2
      PLUGINS_LAVASRC_DEEZER_MASTER_DECRYPTION_KEY: ${DEEZER_KEY:?No Deezer key provided}
      # PLUGINS_LAVASRC_YANDEXMUSIC_ACCESSTOKEN: $YANDEX_TOKEN
      METRICS_PROMETHEUS_ENABLED: true
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_LAVALINK: INFO
      LOGGING_REQUEST_ENABLED: true
      LOGGING_LOGBACK_ROLLING_POLICY_MAX_FILE_SIZE: 100MB
      LOGGING_LOGBACK_ROLLING_POLICY_MAX_HISTORY: 30
